services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - SA_PASSWORD=AzureDevOps!
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - ./datadocker:/var/opt/mssql/data
  api:
    image: api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=master;User=sa;Password=AzureDevOps!;TrustServerCertificate=True